name: Deploy Newest Mavencrest AMI

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR"

      - name: Show OIDC claims
        shell: bash
        run: |
          RESPONSE=$(curl -sSf \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          TOKEN=$(echo "$RESPONSE" | jq -r '.value')
          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)

          PAYLOAD="${PAYLOAD//-/+}"
          PAYLOAD="${PAYLOAD//_/\/}"

          case $((${#PAYLOAD} % 4)) in
            2) PAYLOAD="${PAYLOAD}==" ;;
            3) PAYLOAD="${PAYLOAD}=" ;;
          esac

          echo "$PAYLOAD" | base64 --decode | jq '{sub, aud, repository, ref}'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::063899249655:role/github-mavencrest-deploy
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="prod.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="prod.tfvars"
