name: Deploy Newest Mavencrest AMI

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="prod.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="prod.tfvars"
